definitions:
  main.reloadRulesResponse:
    properties:
      newRules:
        items:
          $ref: '#/definitions/main.rule'
        type: array
      reloaded:
        type: boolean
      ruleErr:
        items:
          $ref: '#/definitions/main.ruleError'
        type: array
      yamlErr:
        type: string
    type: object
  main.response:
    properties:
      allowed:
        type: boolean
      status:
        $ref: '#/definitions/main.status'
        type: object
      uid:
        type: string
    type: object
  main.rule:
    properties:
      key:
        type: string
      name:
        type: string
      value:
        $ref: '#/definitions/main.value'
        type: object
    type: object
  main.ruleError:
    properties:
      err:
        type: string
      rulename:
        type: string
    type: object
  main.status:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  main.validRulesResponse:
    properties:
      errors:
        items:
          $ref: '#/definitions/main.ruleError'
        type: array
      rulesValid:
        type: boolean
    type: object
  main.value:
    properties:
      regex:
        type: string
    type: object
  main.webhookResponse:
    properties:
      apiVersion:
        type: string
      kind:
        type: string
      response:
        $ref: '#/definitions/main.response'
        type: object
    type: object
info:
  contact:
    name: GitHub
    url: https://github.com/circa10a/k8s-label-rules-webhook/
  description: A kubernetes webhook to standardize labels on resources
  license:
    name: MIT
    url: https://github.com/circa10a/k8s-label-rules-webhook/blob/master/LICENSE
  title: k8s-label-rules-webhook
  version: 0.1.0
paths:
  //:
    post:
      description: Respond to k8s with approval or rejection of labels compared against
        the ruleset
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.webhookResponse'
      summary: Respond to k8s with approval or rejection of labels compared against
        the ruleset
  /reload:
    post:
      description: Hot reload ruleset file into memory without downtime
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.reloadRulesResponse'
            type: array
      summary: Reload ruleset file
  /rules:
    get:
      description: Show current ruleset being used to validate labels against
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.rule'
            type: array
      summary: Display loaded rules
  /validate:
    get:
      description: Validate regex of every rule in ruleset, respond with rule errors
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.validRulesResponse'
      summary: Validate regex of all loaded rules
swagger: "2.0"
