name: Test
on: [
  push,
  pull_request
]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        env:
          GIN_MODE: release
          METRICS: true
        run: |
          go test -coverprofile=coverage.txt ./... | sed '/ERRO/d; /level=error/d; /printer.go/d'
          if ! [ $(grep -o "[0-9]\+\.[0-9]\+\.[0-9]\+" api/swagger.json) = $(grep -o "[0-9]\+\.[0-9]\+\.[0-9]\+" main.go ) ]; then
            echo "Update version in main.go and run make docs before committing"
            exit 1
          fi
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
